### ISSUE TITLE
Query returns a LazyBSONList

### ISSUE THREAD

**Issue by Yuyuu** [MongoLink/mongolink#66]
Hello,
I've been stuck on an issue for some time and I'm not able to precisely identify the cause.
The requests made from a session sometimes return a LazyBSONList which produces two errors:

- CollectionMapper.populate (on query) : the LazyBSONList cannot be cast to BasicDBList ;

- ListVisitor.visit (on flush) : Lists.newArrayList(getOrigin()) uses the toArray() method on the given list. However this method is not supported by the LazyBSONList class.

I'm actually not sure that it is not linked to my implementation but since I can't find a way to fix this without touching mongolink's code, I was wondering if the issue had already been encountered.

**Comment by BodySplash** [comment]
Indeed I encountered the very same error some times ago.

Updating mongolink to the last version should do the trick. Let me know if it fixed your problem.

**Comment by Yuyuu** [comment]
I'm using version 1.2.1.
The simplest case of it happening is inside a TimerTask or a (quartz) Job.

**Comment by BodySplash** [comment]
Hum I may have missed a few parts during my refactoring. I'll look into it.

**Comment by BodySplash** [comment]
Ok can you give a try to the last SNAPSHOT version ? (1.2.2-SNAPSHOT, available on this repository : https://oss.sonatype.org/content/repositories/snapshots/)

**Comment by Yuyuu** [comment]
Thank you for taking the time.
This one might be a little more annoying:
```
java.lang.UnsupportedOperationException: Read Only
    at org.bson.LazyBSONList.removeAll(LazyBSONList.java:201)
    at org.mongolink.domain.updateStrategy.ListVisitor.removeIfNeeded(ListVisitor.java:59)
    at org.mongolink.domain.updateStrategy.ListVisitor.visit(ListVisitor.java:44)
```
It's fine for the previous ones though

**Comment by BodySplash** [comment]
Arg :) It should be ok now, you can refresh your snapshot version. Thank you for reporting this issue.

**Comment by Yuyuu** [comment]
It looks all right, thanks!
